---
stages:
  - validate
  - deploy

before_script:
  - pip install pelican

#variables:
#  GET_SOURCES_ATTEMPTS: "5"

job1:
  stage: validate
  before_script:
    - ls
  script:
    - ls
    - ls
  after_script:
    - ls
  tags:
    - ldi-blog

job2:
  stage: deploy
  script:
    - ls
  tags:
    - ldi-blog