---
# Run all tests
stages:
  - validate
  - deploy

#before_script:
#  -

#variables:
  #GET_SOURCES_ATTEMPTS: "5"

job1:
  stage: validate
#  before_script:
#    -
#  script:
#    -
#    -
#  after_script:
#    -
  tags:
    - ldi-blog

job2:
  stage: deploy
#  script:
#    -
#  tags:
#    - ldi-blog
